#
# Pints functional testing command line utility.
#
# This file is part of Pints Functional Testing.
#  Copyright (c) 2017-2019, University of Oxford.
#  For licensing information, see the LICENSE file distributed with the Pints
#  functional testing software package.
#

trigger: none

pr: none

schedules:
- cron: "0 * * * *"
  displayName: Hourly next functional test
  branches:
    include:
    - master
  always: true

jobs:

- job: RunEverything
  
  displayName: Master job to run all steps
  
  variables:
    funkDir: /home/pints/functional-testing

  pool:
    name: 'pints-skip'

  timeoutInMinutes: 150 # 2.5 hour failsafe on entire job

  steps:

  - checkout: none # don't actually check out source - we work on an existing directory

  - script: git pull
    workingDirectory: $(funkDir)
    displayName: Update pints@skip functional-testing repo

  - script: ./funk run --next --plot -r 5
    workingDirectory: $(funkDir)
    displayName: Run next test
    timeoutInMinutes: 150 # 2.5 hour failsafe on script

  - script: ./funk analyse --last
    workingDirectory: $(funkDir)
    displayName: Analyse test
    failOnStderr: true # this is what reports a failure, due to printing to stderr in __main__.py

  - script: ./funk report
    workingDirectory: $(funkDir)
    displayName: Create report
    condition: always() # run even if the test fails

  - script: ./funk commit
    workingDirectory: $(funkDir)
    displayName: Commit results
    condition: always() # run even if the test fails
