#!/usr/bin/env python3

import pfunk

fname = 'test.txt'

w = pfunk.io.ResultWriter(fname, overwrite=True)
w['x'] = 5
w['y'] = 6
print(w)
w.write()

r = pfunk.io.ResultReader(fname)
print(len(r))
print(r['x'])
print(r['y'])
print(r)
